apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgpool.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pgpool.name" . }}
    helm.sh/chart: {{ include "pgpool.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: pgpool-psql
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: pgpool-psql
  selector:
    app.kubernetes.io/name: {{ include "pgpool.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
