{{- range .Values.configmaps }}
{{- if .create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name | default (printf "%s-%s" $.Release.Name .name) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "jovvix.labels" $ | nindent 4 }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- end }}
