{{- range .Values.secrets }}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .fullNameOverride | default (printf "%s-%s" $.Release.Name .name) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "jovvix.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}
