apiVersion: v2
appVersion: "0.13.0"
description: NVR With Realtime Object Detection for IP Cameras
name: frigate
version: 1.1.0
keywords:
  - tensorflow
  - coral
  - ml
maintainers:
  - name: Improwised
