{{- if and .Values.postgres.enabled .Values.postgres.secret.enabled }}
{{- if not .Values.postgres.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: db-{{ include "jovvix.fullname" . }}
  labels:
    {{- include "jovvix.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.secret.username | quote }}
  password: {{ include "jovvix.dbPassword" . | quote }}
{{- end }}
{{- end }}
