{{- if and .Values.kratos.enabled .Values.kratos.secrets.enabled }}
{{- if not .Values.kratos.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kratos.secret.nameOverride }}
  labels:
    {{- include "jovvix.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=%s&search_path=kratos" .Values.database.username (include "jovvix.dbPassword" .) (include "jovvix.databaseHost" .) (.Values.database.port | int) .Values.database.name .Values.database.sslMode | quote }}
  secretsDefault: {{ include "jovvix.kratos.secretsDefault" . | quote }}
  secretsCookie: {{ include "jovvix.kratos.secretsCookie" . | quote }}
  secretsCipher: {{ include "jovvix.kratos.secretsCipher" . | quote }}
  smtpConnectionURI: {{ .Values.kratos.secrets.smtpConnectionURI | required "kratos.secrets.smtpConnectionURI is required (helm install --set 'kratos.secrets.smtpConnectionURI=smtp://user:pass@smtp.example.com:587/')" | quote }}
{{- end }}
{{- end }}
