{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jovvix.fullname" . }}-db
  labels:
    {{- include "jovvix.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "jovvix.fullname" . }}-db
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      {{- include "jovvix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "jovvix.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      terminationGracePeriodSeconds: {{ .Values.postgres.terminationGracePeriodSeconds }}
      {{- with .Values.global.security.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ default .Chart.AppVersion .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          {{- with .Values.global.security.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.port }}
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "db-%s" (include "jovvix.fullname" .)) .Values.postgres.secret.existingSecret }}
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}
          {{- if .Values.postgres.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.database.username | quote }}
            initialDelaySeconds: {{ .Values.postgres.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.livenessProbe.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.database.username | quote }}
            initialDelaySeconds: {{ .Values.postgres.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.livenessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: {{ include "jovvix.fullname" . }}-db-initdb
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass | quote }}
        {{- else if .Values.postgres.storage.storageClass }}
        storageClassName: {{ .Values.postgres.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
{{- end }}
