{{- if and .Values.valkey.enabled .Values.valkey.secret.enabled }}
{{- if not .Values.valkey.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.valkey.secret.name | default (printf "%s-valkey" (include "jovvix.fullname" .)) }}
  labels:
    {{- include "jovvix.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ include "jovvix.redisPassword" . | quote }}
{{- end }}
{{- end }}
