kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "apexkube.labels" . | nindent 4 }}
  name: {{ include "apexkube.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "users"
  - "groups"
  - "serviceaccounts"
  verbs:
  - "impersonate"

- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"

- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "userextras/scopes"
  - "userextras/remote-client-ip"
  verbs:
  - "impersonate"

- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "tokenreviews"
  verbs:
  - "create"
  - "get"
  - "list"
  - "watch"
  - "update"

# apexkube init container requires to list services in order to get
# load balancer hostname
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"

# Access to platformengineers.io CRDs
- apiGroups:
  - "organization.platformengineers.io"
  resources:
  - "User"
  - "Account"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "delete"
