prefixWithReleaseName:
  enabled: true
services:
  - name: frontend
    image:
      repository: nginx
      tag: latest
    healthcheck:
      enabled: true
      type: httpGet
      path: /
      port: http
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 2
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    ingress:
      hosts:
        - host: test.pdb.local
          paths:
            - path: /abc
              pathType: Prefix
              servicePort: http
  - name: ancillary-service
    image:
      repository: nginx
      tag: latest
    podDisruptionBudget:
      enabled: false
    ingress:
      hosts:
        - host: test.pdb.local
          paths:
            - path: /xyz
              pathType: Prefix
              servicePort: http
  - name: appconfig-service
    image:
      repository: nginx
      tag: latest
    ingress:
      hosts:
        - host: test.pdb.local
          paths:
            - path: /test
              pathType: Prefix
              servicePort: http
serviceTemplate:
  podDisruptionBudget:
    enabled: true
    minAvailable: 4
    # maxUnavailable: 2
  healthcheck:
    enabled: true
    type: httpGet
    path: /
    port: http
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
  service:
    enabled: true
    ports:
      - name: http
        port: 80
        targetPort: http
        protocol: TCP
  ingress:
    enabled: true
    className: nginx
    tls: []
