{{- range .Values.cronJobs }}
---
apiVersion: {{ include "cronjob.apiVersion" $ }}
kind: CronJob
metadata:
{{- if $.Values.prefixWithReleaseName.enabled }}
  name: "{{ $.Release.Name }}-{{ .name | default $.Values.cronJobTemplate.name }}"
{{- else}}
  name: "{{ .name | default $.Values.cronJobTemplate.name }}"
{{- end }}
  labels:
    {{- include "polymorphic-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "{{ .name | default $.Values.cronJobTemplate.name }}"
  annotations:
    linkerd.io/inject: disabled
{{- with .annotations | default $.Values.cronJobTemplate.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit  | default $.Values.cronJobTemplate.successfulJobsHistoryLimit | default 0 }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit   | default $.Values.cronJobTemplate.failedJobsHistoryLimit | default 0 }}
  schedule: {{ .schedule | quote }}
  suspend: {{ .suspend | default false }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .imagePullSecrets }}
          imagePullSecrets:
{{ toYaml .imagePullSecrets | indent 12 }}
          {{- else if $.Values.cronJobTemplate.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml $.Values.cronJobTemplate.imagePullSecrets | indent 12 }}
          {{- else }}
          {{- if $.Values.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml $.Values.imagePullSecrets | indent 12 }}
          {{- end }}
          {{- end }}
          restartPolicy: Never
          containers:
{{- $cronName := .name | default $.Values.cronJobTemplate.name }}
{{ include "polymorphic-app.containerSpec" (dict
  "item" .
  "template" $.Values.cronJobTemplate
  "root" $
  "containerName" $cronName
) | indent 12 }}
          {{- with .securityContext | default $.Values.cronJobTemplate.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .affinity | default $.Values.cronJobTemplate.affinity }}
          affinity:
          {{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .tolerations | default $.Values.cronJobTemplate.tolerations }}
          tolerations:
          {{ toYaml . | indent 12 }}
          {{- end }}
          volumes:
      {{- if .volumes }}
{{ toYaml .volumes | indent 12 }}
      {{- end }}
      {{- if $.Values.volumes }}
{{ toYaml $.Values.volumes | indent 12 }}
      {{- end }}
      {{- if $.Values.cronJobTemplate.volumes }}
{{ toYaml $.Values.cronJobTemplate.volumes | indent 12 }}
      {{- end }}
{{- end }}
