{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
{{- if $.Values.prefixWithReleaseName.enabled }}
  name: "{{ $.Release.Name }}-{{ .name | default $.Values.jobTemplate.name }}"
{{- else}}
  name: "{{ .name | default $.Values.jobTemplate.name }}"
{{- end }}
  labels:
    {{- include "polymorphic-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "{{ .name | default $.Values.jobTemplate.name }}"
  annotations:
    linkerd.io/inject: disabled
{{- with .annotations | default $.Values.jobTemplate.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "polymorphic-app.labels" $ | nindent 8 }}
        app.kubernetes.io/component: "{{ .name | default $.Values.jobTemplate.name }}"
    spec:
      {{- if .imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .imagePullSecrets | indent 8 }}
      {{- else if $.Values.jobTemplate.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml $.Values.jobTemplate.imagePullSecrets | indent 8 }}
      {{- else }}
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml $.Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- end }}
      restartPolicy: Never
      containers:
{{- $jobName := .name | default $.Values.jobTemplate.name }}
{{ include "polymorphic-app.containerSpec" (dict
  "item" .
  "template" $.Values.jobTemplate
  "root" $
  "containerName" $jobName
) | indent 8 }}
      {{- with .securityContext | default $.Values.jobTemplate.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .affinity | default $.Values.jobTemplate.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .tolerations | default $.Values.jobTemplate.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      {{- if .volumes }}
{{ toYaml .volumes | indent 8 }}
      {{- end }}
      {{- if $.Values.volumes }}
{{ toYaml $.Values.volumes | indent 8 }}
      {{- end }}
      {{- if $.Values.jobTemplate.volumes }}
{{ toYaml $.Values.jobTemplate.volumes | indent 8 }}
      {{- end }}
{{- end }}
