{{- range .Values.workers }}
---
apiVersion: {{ include "deployment.apiVersion" $ }}
kind: Deployment
metadata:
  {{- if $.Values.prefixWithReleaseName.enabled }}
  name: "{{ $.Release.Name }}-{{ .name | default $.Values.workerTemplate.name }}"
  {{- else }}
  name: "{{ .name | default $.Values.workerTemplate.name }}"
  {{- end }}
  labels:
    {{- include "polymorphic-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "{{ .name | default $.Values.workerTemplate.name }}"
{{- with .annotations | default $.Values.workerTemplate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 100%
  replicas: {{ if ne .minReplicaCount nil }}{{ .minReplicaCount }}{{ else }}{{ $.Values.workerTemplate.minReplicaCount }}{{ end }}
  selector:
    matchLabels:
      {{- include "polymorphic-app.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: "{{ .name | default $.Values.workerTemplate.name }}"
  template:
    metadata:
      labels:
        {{- include "polymorphic-app.labels" $ | nindent 8 }}
        app.kubernetes.io/component: "{{ .name | default $.Values.workerTemplate.name }}"
    spec:
{{- include "polymorphic-app.podSpec" (dict "item" . "root" $ "template" $.Values.workerTemplate "type" "worker") | indent 6 }}

{{- if .autoscaling | default $.Values.workerTemplate.autoscaling }}
---
apiVersion: {{ include "hpa.apiVersion" $ }}
kind: HorizontalPodAutoscaler
metadata:
  {{- if $.Values.prefixWithReleaseName.enabled }}
  name: "{{ $.Release.Name }}-{{ .name | default $.Values.workerTemplate.name }}"
  {{- else }}
  name: "{{ .name | default $.Values.workerTemplate.name }}"
  {{- end }}
  labels:
    {{- include "polymorphic-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "{{ .name | default $.Values.workerTemplate.name }}"
spec:
  scaleTargetRef:
    apiVersion: {{ include "deployment.apiVersion" $ }}
    kind: Deployment
    {{- if $.Values.prefixWithReleaseName.enabled }}
    name: "{{ $.Release.Name }}-{{ .name | default $.Values.workerTemplate.name }}"
    {{- else }}
    name: "{{ .name | default $.Values.workerTemplate.name }}"
    {{- end }}
  minReplicas: {{ .minReplicaCount | default $.Values.workerTemplate.minReplicaCount }}
  maxReplicas: {{ .maxReplicaCount | default $.Values.workerTemplate.maxReplicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .averageUtilization | default $.Values.workerTemplate.averageUtilization }}
{{- end }}
{{- end }}
