{{- range .Values.workers }}
---
apiVersion: {{ include "deployment.apiVersion" $ }}
kind: Deployment
metadata:
  {{- if $.Values.prefixWithReleaseName.enabled }}
  name: "{{ $.Release.Name }}-{{ .name | default $.Values.workerTemplate.name }}"
  {{- else }}
  name: "{{ .name | default $.Values.workerTemplate.name }}"
  {{- end }}
  labels:
    {{- include "polymorphic-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "{{ .name | default $.Values.workerTemplate.name }}"
{{- with .annotations | default $.Values.workerTemplate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 100%
  replicas: {{ if ne .minReplicaCount nil }}{{ .minReplicaCount }}{{ else }}{{ $.Values.workerTemplate.minReplicaCount }}{{ end }}
  selector:
    matchLabels:
      {{- include "polymorphic-app.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: "{{ .name | default $.Values.workerTemplate.name }}"
  template:
    metadata:
      labels:
        {{- include "polymorphic-app.labels" $ | nindent 8 }}
        app.kubernetes.io/component: "{{ .name | default $.Values.workerTemplate.name }}"
    spec:
      {{- if .imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .imagePullSecrets | indent 8 }}
      {{- else if $.Values.workerTemplate.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml $.Values.workerTemplate.imagePullSecrets | indent 8 }}
      {{- else }}
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml $.Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default $.Values.workerTemplate.terminationGracePeriodSeconds }}
      containers:
{{- $workerName := .name | default $.Values.workerTemplate.name }}
{{- $workerProbe := .probe | default $.Values.workerTemplate.probe }}
{{ include "polymorphic-app.containerSpec" (dict
  "item" .
  "template" $.Values.workerTemplate
  "root" $
  "containerName" $workerName
  "probeConfig" $workerProbe
) | indent 8 }}
      {{- with .dnsConfig | default $.Values.workerTemplate.dnsConfig }}
      dnsConfig:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .securityContext | default $.Values.workerTemplate.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      {{- if .volumes }}
{{ toYaml .volumes | indent 8 }}
      {{- end }}
      {{- if $.Values.volumes }}
{{ toYaml $.Values.volumes | indent 8 }}
      {{- end }}
      {{- if $.Values.workerTemplate.volumes }}
{{ toYaml $.Values.workerTemplate.volumes | indent 8 }}
      {{- end }}
    {{- with .nodeSelector | default $.Values.workerTemplate.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .affinity | default $.Values.workerTemplate.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .tolerations | default $.Values.workerTemplate.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

{{- if .autoscaling | default $.Values.workerTemplate.autoscaling }}
---
apiVersion: {{ include "hpa.apiVersion" $ }}
kind: HorizontalPodAutoscaler
metadata:
{{- if $.Values.prefixWithReleaseName.enabled }}
  name: "{{ $.Release.Name }}-{{ .name | default $.Values.workerTemplate.name }}"
{{- else }}
  name: "{{ .name | default $.Values.workerTemplate.name }}"
{{- end }}
  labels:
    {{- include "polymorphic-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "{{ .name | default $.Values.workerTemplate.name }}"
spec:
  scaleTargetRef:
    apiVersion: {{ include "deployment.apiVersion" $ }}
    kind: Deployment
    {{- if $.Values.prefixWithReleaseName.enabled }}
    name: "{{ $.Release.Name }}-{{ .name | default $.Values.workerTemplate.name }}"
    {{- else }}
    name: "{{ .name | default $.Values.workerTemplate.name }}"
    {{- end }}
  minReplicas: {{ .minReplicaCount | default $.Values.workerTemplate.minReplicaCount }}
  maxReplicas: {{ .maxReplicaCount | default $.Values.workerTemplate.maxReplicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .averageUtilization | default $.Values.serviceTemplate.averageUtilization }}
{{- end }}
{{- end }}
