apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asciinema-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "asciinema-server.name" . }}
    helm.sh/chart: {{ include "asciinema-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  SECRET_KEY_BASE: {{ if .Values.server.secretKeyBase -}}{{ .Values.server.secretKeyBase | quote }}{{ else }}{{ randAlphaNum 64 | b64enc | quote}}{{ end -}}
  {{- range $key, $value := .Values.extraEnvs }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
