style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: n
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - ci
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      ci: CI
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  merges:
    pattern: "^Merge branch '(\\w+)'$"
    pattern_maps:
      - Source
  notes:
    keywords:
      - BREAKING CHANGE
