apiVersion: v2
name: healthchecks
description: A Helm chart for Kubernetes
maintainers:
  - email: rakshit@improwised.com
    name: rakshit
type: application
version: 1.1.1
appVersion: 2.7.0
sources:
  - https://github.com/healthchecks/healthchecks
dependencies:
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled,global.postgresql.enabled
