apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ .Values.talosControlPlane.name }}
  namespace: {{ .Values.talosControlPlane.namespace }}
spec:
  replicas: {{ .Values.talosControlPlane.spec.replicas }}
  version: {{ .Values.talosControlPlane.spec.version }}
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: {{ .Values.talosControlPlane.spec.infrastructureTemplate.name }}
    namespace: {{ .Values.talosControlPlane.spec.infrastructureTemplate.namespace }}
  controlPlaneConfig:
    controlplane:
      talosVersion: {{ .Values.talosControlPlane.spec.controlPlaneConfig.controlplane.talosVersion }}
      generateType: {{ .Values.talosControlPlane.spec.controlPlaneConfig.controlplane.generateType }}
      strategicPatches:
              - |
                - op: replace
                  path: /machine/install
                  value:
                    disk: /dev/sda
                    extensions:
                      - image: ghcr.io/siderolabs/qemu-guest-agent:9.2.0
                - op: add
                  path: /machine/install/extraKernelArgs
                  value:
                    - net.ifnames=0
                - op: add
                  path: /machine/network/interfaces
                  value:
                    - interface: eth0
                      dhcp: false
                      vip:
                        ip: {{ .Values.talosControlPlane.spec.controlPlaneConfig.controlplane.ip }}
