apiVersion: v2
name: pgcat
description: A Helm chart for PgCat a PostgreSQL pooler and proxy (like PgBouncer) with support for sharding, load balancing, failover and mirroring.
maintainers:
  - name: Wildcard
    email: support@w6d.io
appVersion: "1.1.1"
version: 0.1.1
keywords:
  - postgresql
  - pgcat
  - connection-pooling
  - database
home: https://github.com/Improwised/charts/tree/main/charts/polymorphic-app
sources:
  - https://github.com/Improwised/charts
annotations:
  artifacthub.io/links: |
    - name: GitHub
      url: https://artifacthub.io/packages/helm/improwised/polymorphic-app
  artifacthub.io/maintainers: |
    - name: Wildcard
      email: support@w6d.io
