apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "n8n-helm.fullname" . }}-config
  labels:
    {{- include "n8n-helm.common.labels.standard" . | nindent 4 }}
    app: {{ template "n8n-helm.fullname" . }}
data:
  DB_TYPE: postgresdb
  DB_POSTGRESDB_DATABASE: {{ default "postgres" .Values.postgresql.postgresqlDatabase | quote }}
  DB_POSTGRESDB_HOST: {{ template "n8n-helm.dbhost" . }}
  DB_POSTGRESDB_PORT: {{ .Values.postgresql.service.port | quote }}
  DB_POSTGRESDB_USER: {{ default "postgres" .Values.postgresql.postgresqlUsername | quote }}
  {{- if .Values.auth.enable }}
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: {{ default "nodemation" .Values.auth.n8nAuthUsername | quote }}
  {{- end }}
