{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n-helm.fullname" . }}-data
  labels:
    {{- include "n8n-helm.common.labels.standard" . | nindent 4 }}
spec:
  {{ include "n8n-helm.storageClass" . }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
