{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "n8n-helm.fullname" . }}-secrets
  labels:
    {{- include "n8n-helm.common.labels.standard" . | nindent 4 }}
    app: {{ template "n8n-helm.fullname" . }}
type: Opaque
data:
  #DB_POSTGRESDB_PASSWORD
  postgresqlDbPass: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}

  {{- if .Values.auth.enabled }}
  #N8N_BASIC_AUTH_PASSWORD
  n8nAuthPass: {{ default "nodemation" .Values.auth.n8nAuthPass | b64enc | quote }}
  {{- end -}}
{{- end }}
