---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frigate.fullname" . }}-pv-claim
  labels:
    app: frigate
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
