apiVersion: v1
kind: Secret
metadata:
  name: {{ template "frigate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "frigate.name" . }}
    helm.sh/chart: {{ include "frigate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  config.yml: |
{{ .Values.config | indent 4 }}
