# Default values for erpnext.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nginxImage:
  repository: docker.io/improwised/erpnext-nginx
  tag: v13.4.1
  pullPolicy: IfNotPresent
  # nginxConfig: |
  #   # custom /etc/nginx/conf.d/default.conf

pythonImage:
  repository: docker.io/improwised/erpnext-worker
  tag: v13.4.1
  pullPolicy: IfNotPresent

socketIOImage:
  repository: frappe/frappe-socketio
  tag: v13.4.1
  pullPolicy: IfNotPresent

redis:
  image:
    repository: bitnami/redis
    tag: 5.0.10-debian-10-r105
    pullPolicy: IfNotPresent
  extraEnv:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"

mariadb:
  enabled: true
  auth:
    rootPassword: mariadb # pragma: allowlist secret
  primary:
    persistence:
      enabled: false
    ## Below, there are some override configs for supporting barracuda engine for Erpnext
    configuration: |-
      [mysql]                                         # override configuration
      default-character-set=utf8mb4                   # override configuration

      [mysqld]
      innodb-file-format=barracuda                    # override configuration
      innodb-file-per-table=1                         # override configuration
      innodb-large-prefix=1                           # override configuration
      character-set-client-handshake=FALSE            # override configuration
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=utf8mb4                     # override from UTF8
      collation-server=utf8mb4_unicode_ci              # override utf8_general_ci UTF8

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

migrateJob:
  # Set this to true to run migrate as part of helm install/upgrade
  enable: false
  backup: false

securityContext:
  capabilities:
    add:
      - CHOWN
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

persistence:
  worker:
    enabled: true
    # existingClaim: ""
    size: 5Gi
    # storageClass: "local-path"
  logs:
    enabled: true
    # existingClaim: ""
    size: 5Gi
    # storageClass: "local-path"

volumePermissions:
  enabled: true
