{{- if .Values.ingress.enabled }}
{{- if .Values.config.ldapsCertificate.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "glauth.fullname" . }}-ldaps-tls
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
spec:
  secretName: {{ include "glauth.fullname" . }}-ldaps-tls
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ .host }}
  {{- end }}
  issuerRef:
    name: {{ required "MUST provide Certificate issuer name" .Values.config.ldapsCertificate.issuerName }}
    kind: {{ default "ClusterIssuer" .Values.config.ldapsCertificate.issuerKind }}
    group: {{ default "cert-manager.io" .Values.config.ldapsCertificate.issuerGroup }}
{{- end }}
{{- end }}
