{{- if .Values.dbRootPassword }}
apiVersion: v1
data:
  dbRootPassword: {{ .Values.dbRootPassword | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
{{- end }}
